build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
  # complexity: 2
  # LongParameterList: 1
  # style: 1
  # comments: 1

config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.,: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'
  #  - 'LiteFindingsReport'

style:
  active: true
  ForbiddenMethodCall:
    active: true
    methods:
      - reason: 'The javafx-built in ObservableValue.map function handles null values in an unusual and in Kotlin undesired way. Use map2() instead.'
        value: 'javafx.beans.value.ObservableValue.map'
      - reason: 'The javafx-built in ObservableValue.map function handles null values in an unusual and in Kotlin undesired way. Use map2() instead.'
        value: 'javafx.beans.property.SimpleObjectProperty.map'
